name: Build & Release Firmware for ESP32-C6

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 📦 Checkout code
      uses: actions/checkout@v3

    - name: 🔧 Install Arduino CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
        sudo mv bin/arduino-cli /usr/local/bin/
        arduino-cli version

    - name: 🔧 Set up Arduino
      run: |
        arduino-cli config init
        arduino-cli config set library.enable_unsafe_install true
        arduino-cli core update-index
        arduino-cli core install esp32:esp32@3.2.0
        arduino-cli lib install "IRremote"
        arduino-cli lib install "BLE"

    - name: 🏗️ Create build directory
      run: mkdir -p compiled_binaries

    - name: 🚀 Build all firmware
      run: |
        chmod +x ./build_all_esp32c6.sh
        ./build_all_esp32c6.sh

    - name: 📦 Package artifacts
      run: |
        mkdir -p artifacts
        find compiled_binaries -name "*.bin" -exec cp {} artifacts \;

    - name: 📤 Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: firmware-binaries
        path: artifacts/*.bin

    - name: 🏷️ Create release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: artifacts/*.bin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}