name: Build & Release Firmware for ESP32-C6

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 📦 Checkout code
      uses: actions/checkout@v3

    - name: 🔧 Install Arduino CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
        sudo mv bin/arduino-cli /usr/local/bin/

    - name: 🔧 Set up Arduino core for ESP32-C6
      run: |
        arduino-cli config init
        arduino-cli config set library.enable_unsafe_install true
        arduino-cli config set directories.user "$PWD"
        arduino-cli core update-index
        arduino-cli core install esp32:esp32

    - name: 🧹 Make build script executable
      run: chmod +x ./build_all_esp32c6.sh

    - name: 🚀 Build all firmware
      run: ./build_all_esp32c6.sh

    - name: 🐞 Show .ino.bin files
      run: echo "${{ steps.find_bins.outputs.BIN_FILES }}"
    
    - name: 📦 Find all files in firmware_bins folder
      id: find_all_files
      run: |
        ALL_FILES=$(find firmware_bins -type f | paste -sd ' ' -)
        echo "ALL_FILES=$ALL_FILES" >> $GITHUB_OUTPUT

    - name: 📤 Upload all files to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ steps.find_all_files.outputs.ALL_FILES }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
