name: Build & Release Firmware for ESP32-C6

on:
  push:
    branches:
      - main  # or your preferred branch name
    tags:
      - 'v*'

jobs:
  create-tag:
    if: github.ref == 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Create tag v0.1.0
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git tag -a v0.1.0 -m "Release version 0.1.0"
          git push origin v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: create-tag
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Increased timeout for large downloads

    steps:
    - name: 📦 Checkout code
      uses: actions/checkout@v4
      with:
        ref: v0.1.0  # Checkout the tagged version

    - name: 🔧 Setup Arduino CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
        sudo mv bin/arduino-cli /usr/local/bin/
        arduino-cli version
        arduino-cli config init
        arduino-cli config set library.enable_unsafe_install true
        arduino-cli core update-index
        arduino-cli core install esp32:esp32@3.2.0
        arduino-cli lib install "IRremote"
        arduino-cli lib install "Adafruit NeoPixel"

    - name: 🏗️ Create build directory
      run: mkdir -p compiled_binaries

    - name: 🚀 Build all firmware
      run: |
        chmod +x ./build_all_esp32c6.sh
        ./build_all_esp32c6.sh || true  # Continue even if some fail

    - name: 📦 Package artifacts
      run: |
        mkdir -p artifacts
        # Only copy .ino.bin files (exclude .merged.bin, .partitions.bin, .bootloader.bin)
        find compiled_binaries -name "*.ino.bin" -exec cp {} artifacts \;
        echo "=== Artifacts (.ino.bin only) ==="
        ls -lh artifacts
        echo "=== Failed Build Logs ==="
        find compiled_binaries -name "compile.log" -exec sh -c 'echo "\n{}:"; cat {}' \;

    - name: 📤 Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: firmware-binaries
        path: artifacts/*.bin

    - name: 🏷️ Create release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v0.1.0
        name: Release v0.1.0
        body: Automatic release of firmware version 0.1.0
        files: artifacts/*.bin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}