name: Build All Arduino Projects for ESP32

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🛠️ Install Arduino CLI
        run: |
          wget https://downloads.arduino.cc/arduino-cli/arduino-cli_latest_Linux_64bit.tar.gz
          tar -xzf arduino-cli_latest_Linux_64bit.tar.gz
          chmod +x arduino-cli
          sudo mv arduino-cli /usr/local/bin/
          arduino-cli version

      - name: 📦 Install ESP32 core
        run: |
          arduino-cli config init --overwrite
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

      - name: 🔧 Compile all .ino projects
        run: |
          mkdir -p firmware_bins

          for sketch in $(find . -type f -name "*.ino"); do
            sketch_dir=$(dirname "$sketch")
            sketch_name=$(basename "$sketch" .ino)

            echo "🚧 Compiling $sketch_name in $sketch_dir"

            arduino-cli compile \
              --fqbn esp32:esp32:esp32 \
              --output-dir "firmware_bins/$sketch_name" \
              --build-path "firmware_bins/$sketch_name" \
              --warnings all \
              --verbose \
              "$sketch_dir"
          done

      - name: 📤 Upload all .bin files
        uses: actions/upload-artifact@v4
        with:
          name: all-esp32-binaries
          path: firmware_bins/**/**/*.bin
