name: Build & Release Firmware for ESP32-C6

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 📦 Checkout code
      uses: actions/checkout@v3

    - name: 🔧 Install Arduino CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
        sudo mv bin/arduino-cli /usr/local/bin/

    - name: 🔧 Set up Arduino core for ESP32-C6
      run: |
        arduino-cli config init
        arduino-cli config set library.enable_unsafe_install true
        arduino-cli config set directories.user "$PWD"
        arduino-cli core update-index
        arduino-cli core install esp32:esp32

    - name: 🧹 Make build script executable
      run: chmod +x ./build_all_esp32c6.sh

    - name: 🚀 Build all firmware
      run: ./build_all_esp32c6.sh

    - name: Find firmware .bin files
      id: find_bins
      run: |
        # Create a list of all .bin files with their full paths
        BIN_FILES=$(find firmware_bins -type f -name '*.bin' | awk '{printf "%s ", $0}')
        # Store the list in GitHub outputs
        echo "BIN_FILES=${BIN_FILES%?}" >> $GITHUB_OUTPUT
        # Print for debugging
        echo "Found bin files:"
        echo "$BIN_FILES"
        echo "Full paths:"
        find firmware_bins -type f -name '*.bin' -exec ls -la {} \;

    - name: Upload firmware binaries
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ steps.find_bins.outputs.BIN_FILES }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}