name: Build ESP32-C6 Firmware

on:
  push:
    paths:
      - '**/*.ino'
      - 'build_all_esp32c6.sh'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 📦 Checkout
      uses: actions/checkout@v3

    - name: 🐳 Set up Docker (optional if using Docker container build)
      run: |
        sudo apt update
        sudo apt install -y docker.io
        sudo systemctl start docker
        sudo usermod -aG docker $USER

    - name: 🔧 Install Arduino CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
        sudo mv bin/arduino-cli /usr/local/bin/

    - name: 🔧 Set up Arduino core for ESP32-C6
      run: |
        arduino-cli config init
        arduino-cli config set library.enable_unsafe_install true
        arduino-cli config set directories.user "$PWD"
        arduino-cli core update-index
        arduino-cli core install esp32:esp32
        arduino-cli board listall

    - name: 🧹 Make script executable
      run: chmod +x ./build_all_esp32c6.sh

    - name: 🚀 Build firmware
      run: ./build_all_esp32c6.sh

    - name: 📤 Upload firmware binaries
      uses: actions/upload-artifact@v3
      with:
        name: firmware_bins
        path: firmware_bins/
